[project]
name = "rv.remotes"
r_version = "4.4"

# any CRAN-type repository, order matters. Additional ability to force source package installation
# Example: {alias = "CRAN", url = "https://cran.r-project.org", force_source = true}
repositories = [
    { alias = "PPM", url = "https://packagemanager.posit.co/cran/2024-01-01" },
]

# package to install and any specifications. Any descriptive dependency can have the `install_suggestions` specification
# Examples:
    # "dplyr",
    # {name = "dplyr", repository = "CRAN", force_source = true},
    # {name = "dplyr", git = "https://github.com/tidyverse/dplyr.git", tag = "v1.1.4"},
    # {name = "dplyr", path = "/path/to/local/dplyr"},
dependencies = [
    { name = "rv.remotes", path = ".", dependencies_only = true },
    "devtools",
]


